// Auto-generated by `wrangler types`
interface CloudflareBindings {
  DB: D1Database;
  JWT_SECRET: string;
  OPENAI_API_KEY: string;
  R2: R2Bucket;
  R2_ACCOUNT_ID: string;
  R2_ACCESS_KEY_ID: string;
  R2_SECRET_ACCESS_KEY: string;
}
