import { newId } from "./id.js"
import { registerBlock } from "./registry.js"
import { DEFAULT_FONT_STACK } from "./types.js"
import type { BlockDefinition, EmailPalette, EmailSettings } from "./types.js"

export const DEFAULT_PALETTE: EmailPalette = {
  INK: "#221d15",
  DARK: "#0d0b08",
  GOLD: "#d7b227",
  CREAM_DIM: "#b8ae9d",
}

export const DEFAULT_SETTINGS: EmailSettings = {
  pageBackground: "#f5f1e8",
  cardBorderWidth: 1,
  cardBorderRadius: 4,
  fontFamily: DEFAULT_FONT_STACK,
  files: [],
}

export const DEFAULT_BLOCK_LIBRARY: BlockDefinition[] = [
  {
    type: "header",
    label: "Header / Marca",
    description: "Logo y nombre de la marca",
    defaultProps: {
      brandName: "Tu Marca",
      tagline: "Breve descripción de tu marca",
      align: "center",
      backgroundColor: "#0d0b08",
      paddingY: 24,
      paddingX: 32,
    },
  },
  {
    type: "hero",
    label: "Hero",
    description: "Titular grande + subtítulo",
    defaultProps: {
      title: "¡Un gran titular aquí!",
      subtitle: "Un subtítulo de apoyo para tu mensaje.",
      align: "center",
      paddingY: 40,
      paddingX: 32,
    },
  },
  {
    type: "heading",
    label: "Título",
    description: "Título de sección",
    defaultProps: {
      text: "Título de sección",
      size: 22,
      color: "#0d0b08",
      align: "left",
      paddingY: 16,
      paddingX: 32,
    },
  },
  {
    type: "text",
    label: "Texto",
    description: "Párrafo de texto",
    defaultProps: {
      text: "Escribe aquí tu mensaje. Puedes usar variables como {name}.",
      size: 15,
      color: "#221d15",
      align: "left",
      paddingY: 12,
      paddingX: 32,
    },
  },
  {
    type: "list",
    label: "Lista",
    description: "Viñetas o pasos numerados (3 estilos)",
    defaultProps: {
      items: ["Beneficio 1", "Beneficio 2", "Beneficio 3"],
      icon: "✓",
      variant: "bullets",
      entries: [
        {
          id: newId(),
          title: "Paso 1",
          description: "Describe el primer beneficio o paso del proceso.",
        },
        {
          id: newId(),
          title: "Paso 2",
          description: "Describe el segundo beneficio o paso del proceso.",
        },
        {
          id: newId(),
          title: "Paso 3",
          description: "Describe el tercer beneficio o paso del proceso.",
        },
      ],
      accentColor: "#d7b227",
      radius: 4,
      imageHeight: 168,
      align: "left",
      paddingY: 12,
      paddingX: 32,
    },
  },
  {
    type: "button",
    label: "Botón CTA",
    description: "Botón con enlace",
    defaultProps: {
      label: "¡Quiero mi cupo!",
      href: "",
      backgroundColor: "#d7b227",
      color: "#0d0b08",
      align: "center",
      paddingY: 16,
      paddingX: 32,
    },
  },
  {
    type: "image",
    label: "Imagen",
    description: "Imagen del correo",
    defaultProps: {
      src: "",
      alt: "Imagen",
      width: 480,
      align: "center",
      paddingY: 16,
      paddingX: 32,
    },
  },
  {
    type: "quote",
    label: "Cita / Testimonio",
    description: "Cita con autor",
    defaultProps: {
      text: "Esto cambió por completo mi manera de pensar.",
      author: "Nombre del participante",
      borderColor: "#d7b227",
      align: "left",
      paddingY: 16,
      paddingX: 32,
    },
  },
  {
    type: "columns",
    label: "Columnas",
    description: "Dos columnas con bloques",
    defaultProps: {
      columns: [
        {
          id: newId(),
          blocks: [
            {
              id: newId(),
              type: "text",
              props: { text: "Columna 1", align: "left", paddingY: 0, paddingX: 0 },
            },
          ],
        },
        {
          id: newId(),
          blocks: [
            {
              id: newId(),
              type: "text",
              props: { text: "Columna 2", align: "left", paddingY: 0, paddingX: 0 },
            },
          ],
        },
      ],
      align: "left",
      paddingY: 16,
      paddingX: 32,
      gap: 8,
    },
  },
  {
    type: "container",
    label: "Contenedor",
    description: "Agrupa bloques en una columna",
    defaultProps: {
      blocks: [],
      align: "left",
      paddingY: 16,
      paddingX: 32,
    },
  },
  {
    type: "grid",
    label: "Cuadrícula",
    description: "Fila de celdas con anchos",
    defaultProps: {
      columns: [
        {
          id: newId(),
          width: 50,
          blocks: [
            {
              id: newId(),
              type: "text",
              props: { text: "Celda 1", align: "left", paddingY: 0, paddingX: 0 },
            },
          ],
        },
        {
          id: newId(),
          width: 50,
          blocks: [
            {
              id: newId(),
              type: "text",
              props: { text: "Celda 2", align: "left", paddingY: 0, paddingX: 0 },
            },
          ],
        },
      ],
      layout: "1-2",
      align: "left",
      paddingY: 16,
      paddingX: 32,
      gap: 12,
    },
  },
  {
    type: "divider",
    label: "Divisor",
    description: "Línea separadora",
    defaultProps: {
      color: "#e3dccb",
      paddingY: 8,
      paddingX: 32,
    },
  },
  {
    type: "spacer",
    label: "Espaciador",
    description: "Altura en píxeles",
    defaultProps: {
      height: 24,
    },
  },
  {
    type: "footer",
    label: "Footer",
    description: "Pie legal o de marca (3 estilos)",
    defaultProps: {
      variant: "classic",
      columns: [],
      text: "Recibes este correo por estar registrado en nuestra plataforma.",
      brandName: "Tu Marca",
      align: "center",
      paddingY: 24,
      paddingX: 32,
      gap: 12,
    },
  },
  {
    type: "social",
    label: "Redes sociales",
    description: "Fila de enlaces sociales",
    defaultProps: {
      links: [
        {
          id: newId(),
          label: "Instagram",
          href: "https://instagram.com",
          icon: "◎",
        },
        { id: newId(), label: "X", href: "https://x.com", icon: "X" },
        {
          id: newId(),
          label: "LinkedIn",
          href: "https://linkedin.com",
          icon: "in",
        },
      ],
      mode: "text",
      align: "center",
      paddingY: 16,
      paddingX: 32,
      color: "#221d15",
      accentColor: "#d7b227",
      iconSize: 32,
      gap: 6,
    },
  },
  {
    type: "gallery",
    label: "Galería",
    description: "Galería de imágenes (4 diseños)",
    defaultProps: {
      images: [
        { id: newId(), src: "", alt: "Imagen 1" },
        { id: newId(), src: "", alt: "Imagen 2" },
      ],
      columns: 2,
      variant: "grid",
      radius: 6,
      imageHeight: 0,
      align: "center",
      paddingY: 16,
      paddingX: 32,
    },
  },
  {
    type: "stats",
    label: "Estadísticas",
    description: "Cifras destacadas en fila",
    defaultProps: {
      stats: [
        { id: newId(), value: "500+", label: "Clientes" },
        { id: newId(), value: "98%", label: "Satisfacción" },
        { id: newId(), value: "24/7", label: "Soporte" },
      ],
      align: "center",
      paddingY: 24,
      paddingX: 32,
      accentColor: "#d7b227",
    },
  },
  {
    type: "pricing",
    label: "Precio / Plan",
    description: "Tarjeta de plan con beneficios (3 estilos)",
    defaultProps: {
      variant: "card",
      title: "Plan Pro",
      price: "$29",
      period: "/mes",
      bullets: ["Acceso completo", "Soporte prioritario", "Sin límites"],
      ctaLabel: "Suscribirme",
      ctaHref: "",
      eyebrow: "",
      description: "",
      note: "",
      note2: "",
      heading: "",
      subtitle: "",
      plans: [],
      footnote: "",
      align: "center",
      paddingY: 24,
      paddingX: 32,
      accentColor: "#d7b227",
      textColor: "#221d15",
    },
  },
  {
    type: "product",
    label: "Producto",
    description: "Producto con precio y botón de compra (4 estilos)",
    defaultProps: {
      variant: "card",
      imageUrl: "",
      name: "Nombre del producto",
      description: "Una breve descripción del producto.",
      price: "$49",
      ctaLabel: "Comprar ahora",
      ctaHref: "",
      eyebrow: "",
      heading: "",
      subheading: "",
      products: [
        {
          id: newId(),
          imageUrl: "",
          name: "Producto 1",
          description: "Una breve descripción del producto.",
          price: "$49",
          ctaLabel: "Comprar",
          ctaHref: "",
        },
        {
          id: newId(),
          imageUrl: "",
          name: "Producto 2",
          description: "Una breve descripción del producto.",
          price: "$59",
          ctaLabel: "Comprar",
          ctaHref: "",
        },
      ],
      columns: 2,
      imageHeight: 0,
      radius: 8,
      accentColor: "#d7b227",
      align: "center",
      paddingY: 24,
      paddingX: 32,
    },
  },
  {
    type: "checkout",
    label: "Resumen de pedido",
    description: "Carrito con líneas de producto y botón de compra",
    defaultProps: {
      heading: "Tu carrito te espera",
      lines: [
        {
          id: newId(),
          imageUrl: "",
          name: "Producto 1",
          quantity: "1",
          price: "$49",
        },
        {
          id: newId(),
          imageUrl: "",
          name: "Producto 2",
          quantity: "1",
          price: "$59",
        },
      ],
      ctaLabel: "Finalizar compra",
      ctaHref: "",
      imageHeight: 110,
      radius: 8,
      accentColor: "#4f46e5",
      borderColor: "#e5e7eb",
      align: "center",
      paddingY: 24,
      paddingX: 32,
    },
  },
  {
    type: "testimonial",
    label: "Testimonio",
    description: "Cita con avatar y autor",
    defaultProps: {
      avatarUrl: "",
      quote: "Cambió por completo la forma en que trabajamos.",
      name: "Nombre Apellido",
      role: "Cargo en la empresa",
      align: "left",
      paddingY: 20,
      paddingX: 32,
      accentColor: "#d7b227",
    },
  },
  {
    type: "features",
    label: "Características",
    description: "Cuadrícula de features",
    defaultProps: {
      features: [
        {
          id: newId(),
          icon: "✓",
          title: "Fácil de usar",
          description: "Empieza en minutos, sin configuración.",
        },
        {
          id: newId(),
          icon: "★",
          title: "Potente",
          description: "Todo lo que necesitas en un solo lugar.",
        },
      ],
      columns: 2,
      align: "left",
      paddingY: 20,
      paddingX: 32,
      accentColor: "#d7b227",
    },
  },
  {
    type: "avatar",
    label: "Avatar",
    description: "Foto, nombre y cargo",
    defaultProps: {
      imageUrl: "",
      name: "Nombre Apellido",
      role: "Cargo",
      size: 96,
      align: "center",
      paddingY: 16,
      paddingX: 32,
    },
  },
  {
    type: "code",
    label: "Código",
    description: "Bloque de código monoespaciado",
    defaultProps: {
      code: "npm install create-email-template",
      language: "bash",
      align: "left",
      paddingY: 16,
      paddingX: 32,
      backgroundColor: "#0d0b08",
      color: "#f5f1e8",
    },
  },
  {
    type: "link",
    label: "Enlace",
    description: "Enlace de texto suelto",
    defaultProps: {
      label: "Ver más",
      href: "",
      align: "left",
      paddingY: 8,
      paddingX: 32,
      color: "#a98a1e",
    },
  },
  {
    type: "downloads",
    label: "Archivos / Descargas",
    description: "Lista los archivos subidos en Ajustes (PDF, DOC, XLS…)",
    defaultProps: {
      heading: "Recursos descargables",
      subheading: "",
      buttonLabel: "Descargar",
      accentColor: "#d7b227",
      borderColor: "#e3dccb",
      showSize: true,
      showIcon: true,
      radius: 8,
      emptyText: "",
      align: "left",
      paddingY: 16,
      paddingX: 32,
    },
  },
]

// Registro de definiciones: la librería viva del registry es la fuente para
// normalize/listBlockDefinitions; DEFAULT_BLOCK_LIBRARY sigue siendo el
// snapshot estático exportado por compat.
for (const definition of DEFAULT_BLOCK_LIBRARY) {
  registerBlock({ definition })
}
